language: node_js
node_js:
  - "stable"
cache:
  - directories:
    - node_modules

matrix:
  allow_failures:
    - npm: test
jobs:
  include:
    - stage: "Tests"
      name: "UI Tests"
      script: 
        - npm install
        - npm test
    - stage: "Tests"
      name: "Build Tests"
      script: 
        - npm install
        - npm run build-electron-linux